;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        completion-separator-self-insert-autofilling
        ))

(setq mc/cmds-to-run-once
      '(
        completion-separator-self-insert-command
        smart-beginning-of-line
        ))
