(setq next-line-add-newlines nil)
(setq scroll-step 1)
(setq hscroll-step 1)
(line-number-mode 1)
(column-number-mode 1)
(setq sentence-end-double-space nil)
(setq confirm-kill-emacs 'y-or-n-p)

(global-set-key (kbd "M-1") 'delete-other-windows)
(global-set-key (kbd "M-2") 'split-window-vertically)
(global-set-key (kbd "M-3") 'split-window-horizontally)
(global-set-key (kbd "M-0") 'delete-window)
(global-set-key (kbd "M-N") 'windmove-down)
(global-set-key (kbd "M-P") 'windmove-up)
(global-set-key (kbd "M-O") 'find-file)
(global-set-key (kbd "M-S") 'save-buffer)
(global-set-key (kbd "M-?") 'apropos)