(setq-default coding-system 'utf-8)
(setq-default buffer-coding-system 'utf-8)
(setq-default buffer-file-coding-system 'utf-8)
(setq-default file-name-coding-system 'utf-8)
(setq file-coding-system 'utf-8)
(setq terminal-coding-system 'utf-8)
(setq keyboard-coding-system 'utf-8)
